In [1]:
#install python package - NumPy

In [12]:
#pip install numpy

In [3]:
import numpy as np

In [4]:
myList=[1,2,3,4]

In [5]:
print(myList)

[1, 2, 3, 4]


In [6]:
myList


[1, 2, 3, 4]

In [7]:
type(myList)

list

In [8]:
#dir(np)

In [9]:
#help(np)

In [10]:
arr = np.array(myList)

In [11]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [13]:
#shape of the array
arr.shape

(4,)

In [14]:
arr.size

4

In [16]:
my_lst1=[1,2,3,4]
my_lst2=[5,6,7,8]
my_lst3=[9,10,11,12]
arr = np.array([my_lst1,my_lst2,my_lst3])

In [17]:
type(arr)

numpy.ndarray

In [18]:
arr.shape

(3, 4)

In [19]:
arr.size

12

In [20]:
#numpy array indexing

my_list1=[1,2,3,4,5]
arr = np.array(my_list1)

In [21]:
print(arr[0])

1


In [22]:
#get the second element from the array

print(arr[1])

2


In [30]:
#get the third and forth elements from the following array and add them

print("the third element is: ", arr[2]," and forth element is: ",arr[3])

the third element is:  3  and forth element is:  4


In [31]:
# Access 2D array

my_lst1=[1,2,3,4]
my_lst2=[5,6,7,8]
my_lst3=[9,10,11,12]
arr = np.array([my_lst1,my_lst2,my_lst3])

In [32]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr[1,2]

7

In [35]:
print("2nd element on first row :",arr[0,1])

2nd element on first row : 2


In [37]:
#Access the element on 2nd row, 4th column

arr[1,3]

8

In [40]:
va1Arr = np.array([[1,2,3],[4,5,6]])
#print the variable
#get size
#get shape
#index : first row first element
#index: second row third element

In [47]:
print("printing the variable value",va1Arr)
print("\n")
print("printing the size :",va1Arr.shape)
print("\n")
print("printing the shape :",va1Arr.size)
print("\n")
print("indexing first row first element :",va1Arr[0,0])
print("\n")
print("indexing second row third element :",va1Arr[1,2])

printing the variable value [[1 2 3]
 [4 5 6]]


printing the size : (2, 3)


printing the shape : 6


indexing first row first element : 1


indexing second row third element : 6


In [7]:
#5*5 array
newArr = np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,14],[20,25,30,35,40]])
print("printing the variable value",newArr)
print("\n")
print("printing the size :",newArr.shape)
print("\n")
print("printing the shape :",newArr.size)
print("\n")
print("second element on third row :",newArr[2,1])
print("\n")
print("first element on forth row :",newArr[3,0])

printing the variable value [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 14]
 [20 25 30 35 40]]


printing the size : (5, 5)


printing the shape : 25


second element on third row : 2


first element on forth row : 11


In [10]:
# Negative indexing
mylist=[1,2,3,4,5,6,7]
arr = np.array(mylist)
#print(arr)

va1Arr = np.array([[1,2,3],[4,5,6]])
print(va1Arr)

[[1 2 3]
 [4 5 6]]


In [14]:
va1Arr[1,-2]

5

In [19]:
# Numpy Array slicing 1D
mylist=[1,2,3,4,5,6,7,8,9,10]
arr = np.array(mylist)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
# arr[start:end]
arr[0:4]

array([1, 2, 3, 4])

In [20]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[:2]

array([1, 2])

In [22]:
arr[-3:-1]

array([8, 9])

In [23]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
#step
arr[::2]

array([1, 3, 5, 7, 9])

In [25]:
arr[1::3]

array([2, 5, 8])

In [26]:
# slicing 2D array
mylist1=[1,2,3,4,5]
mylist2=[2,3,4,5,6]
mylist3=[9,7,6,8,9]

arr=np.array([mylist1,mylist2,mylist3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [27]:
#arr[rowstart:rowend,colstart:colend]
arr[1:,:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [28]:
arr[2:,:]

array([[9, 7, 6, 8, 9]])

In [29]:
arr[:,1:]

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [7, 6, 8, 9]])

In [30]:
arr[:,2:]

array([[3, 4, 5],
       [4, 5, 6],
       [6, 8, 9]])

In [31]:
# A range function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
#step
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [35]:
#lin space
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [36]:
#Numpy data types
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [7]:
arr=np.array([1.0,2.0])
print(arr.dtype)

float64


In [8]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [9]:
arr=np.array(['apple','banana','cherry','bananacherry'])
print(arr.dtype)

<U12


In [16]:
arr=np.array([1,2,3,4,5],dtype=np.int64)
print(arr.dtype)

int64


In [17]:
arr=np.array([1,2,3,4,5],dtype=np.float32)
print(arr.dtype)

float32


In [18]:
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [29]:
#Array math operation
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])


In [30]:
print(x)
print("**")
print(y)

[[1 2]
 [3 4]]
**
[[5 6]
 [7 8]]


In [31]:
x+y

array([[ 6,  8],
       [10, 12]])

In [32]:
x-y

array([[-4, -4],
       [-4, -4]])

In [33]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [34]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [35]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [36]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [37]:
x.shape

(2, 2)

In [38]:
y.shape

(2, 2)

In [41]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8],[9,10]],dtype=np.float64)

In [42]:
x+y

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [43]:
x

array([[1., 2.],
       [3., 4.]])

In [44]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [46]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [47]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [48]:
np.tan(x)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [49]:
# Floor, Ceil , Round
x=np.array([[1.5,2.6],[3.1,4.9]],dtype=np.float64)

In [50]:
x


array([[1.5, 2.6],
       [3.1, 4.9]])

In [51]:
np.floor(x)

array([[1., 2.],
       [3., 4.]])

In [52]:
np.ceil(x)

array([[2., 3.],
       [4., 5.]])

In [53]:
np.round(x)

array([[2., 3.],
       [3., 5.]])

In [54]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
z=np.array([[9,10],[11,12]],dtype=np.float64)

In [55]:
x*y*z

array([[ 45., 120.],
       [231., 384.]])

In [56]:
np.multiply(x,y,z)

array([[ 5., 12.],
       [21., 32.]])

In [22]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
#Numpy array copy 
arr = np.array([1,2,3,4,5])
x = arr

In [14]:
print(arr)

[1 2 3 4 5]


In [15]:
print(x)

[1 2 3 4 5]


In [16]:
arr[0]=100

In [11]:
print(arr)

[100   2   3   4   5]


In [17]:
print(x)

[100   2   3   4   5]


In [18]:
x[1]=100

In [19]:
print(x)

[100 100   3   4   5]


In [26]:
#Numpy array reshaping
arr = np.arange(1,13)
arr.shape

(12,)

In [34]:
arr_new = arr.reshape(4,3)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
arr_new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
#flattening the arrays
#2D----->1D
arr_new.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
#Iterating arrays
arr = np.arange(1,7).reshape(3,2)

In [42]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
for x in arr:
    print(x)

[1 2]
[3 4]
[5 6]


In [44]:
#Joining Numpy Arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [46]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [47]:
#join two 2D arrays along rows (axis=1):
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [48]:
arr1

array([[1, 2],
       [3, 4]])

In [49]:
arr2

array([[5, 6],
       [7, 8]])